### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SlungileAno** [BusinessAnalysis-AI-Innovators/Telemedicine-AI-Platform#8]
@GomolemoN check out this document I made some changes and please add/edit when necessary.
[Documentation.docx](https://github.com/BusinessAnalysis-AI-Innovators/Telemedicine-AI-Platform/files/12372071/Documentation.docx)

**Comment by GomolemoN** [comment]
Okay sure

**Comment by GomolemoN** [comment]
Hey guys so here's the updated file 
[Documentation.docx](https://github.com/BusinessAnalysis-AI-Innovators/Telemedicine-AI-Platform/files/12381336/Documentation.docx)
I added some information about the data that our ML algorithm is going to use, I didn't go into much detail about it because I was thinking that it would be best if we revisit the data section once we start coding and figure out what works for us
I went through it using Grammarly again making a few changes here and there so let me know what you guys think

**Comment by GomolemoN** [comment]
I'm also still working on the decleration but I'll have it ready probably sometime this weekend

**Comment by KhathutsheloMakatu** [comment]
Thanks, will discuss tomorrow morning 😇😇
